### ISSUE TITLE
Mpp files converting incorrectly?

### ISSUE THREAD

**Issue by resistthis13** [ProgSys/pg_disatools#1]
I've tried to use the tx2 converter to open mpp files, and it says "error .MPPs are an achieve[sic] containing multiple files" and they would not open in image editing software. One of the other Disgaea PC modders had a tool that turned the .mpp files into a folder with numerically named files, but when i tried converting those to images, they wouldn't open either.

**Comment by ProgSys** [comment]
Yes it can't open it yet, it is a file containing multiple textures and what looks like geometry.
I am currently changing the gui to Qt. After this I will work on the .MPP files.

**Comment by ProgSys** [comment]
Version v0.3 can now open them.
