### ISSUE TITLE
Unable to use tools, tools look blank.

### ISSUE THREAD

**Issue by verisar** [ProgSys/pg_disatools#11]
Was looking into starting D1/2 and wanted to import some hd sprites but when i go into the Sprite sheet editor its almost completely blank of options, i can view animations but if i try to create a new one nothing is there. I looked on the main page and i didnt see that this needed any dependencies

 but i could have missed something.

Sprite Sheet Editor - Blank interface
TX2 Editor - Blank after import

Tested on Win 10 x64
![capture](https://user-images.githubusercontent.com/15370687/27520703-b4a15176-59d6-11e7-9ac5-ccfd957fd00a.PNG)
![capture2](https://user-images.githubusercontent.com/15370687/27520704-b4f7fd0a-59d6-11e7-8cbb-7c466ded91e6.PNG)

Any other info you need let me know i really want to play these games before i start D3/4 which dont need HD sprites.

**Comment by ProgSys** [comment]
The ui uses QML that are located in the QML folder. If they are blank this means they are not found or not loaded correctly. Did you extrat all the files from the zip? I will have a look on my side if i can find any problem.

**Comment by ProgSys** [comment]
I updated the Sprite Editor it now should display error messages if it fails to load a QML file. 
Can you please copy them over. With them I should be able to determine the cause of the problem. So far I couldn't find anything as on my PC and my laptop everything works fine.

If you plan to create HD sprites then you will most likely run into some problems. The issue is that Disgaea 1 allocates a set amount of memory for all sprites. This means the game can only handle about 10 HD sprites before it runs out of memory and crashes. This is a complete arbitrary limitation by the game and I have no idea why they did it this way. Without modifying the game memory or executable there is no way of fixing it. 😞

**Comment by verisar** [comment]
I fixed the issue, it was when i was unzipping it it was overwriting the files that didnt exist, i solved this by opening 7zip and dragging each item single handedly to a different drive, i didnt install it to any root folders but for some reason it just didnt like my C:.

After i figured it out i went to edit a sprite file i already saw the steam post about only allowing a max number of HD sprites so i was going to run ahead and just do mains but i ran into a color template issue with most of the hd sprites using over 100 colors with max being 32, even when i forced more colors it would mess up the colors when i did layers in editing the frames.

I think ill go ahead and just download whats already online i didnt realize you would have to edit so many animations just for a single character.

Sorry to waste your time, now, if the game didnt have a limitation, then yes i would spend alot of time editing everything to make it HD cause that would be fun imo.

**Comment by ProgSys** [comment]
You can add more colors. I wrote a tutorial about it some time ago: https://github.com/ProgSys/pg_disatools/wiki/Replacing-a-sprite-with-a-HD-version

**Comment by verisar** [comment]
Alright so its looking good i followed the guide, everything is perfect except the sprite in the actual timeline. I have the color temp set to 2 like in the guide but for some reason no matter what i set the very bottom color table to it just looks like the image on the right even though the sprite sheet looks correct.

![capture](https://user-images.githubusercontent.com/15370687/27567683-f6f16836-5ab2-11e7-8ba4-c3162569f391.PNG)

**Comment by verisar** [comment]
Also id just like to say thanks for the help.

**Comment by verisar** [comment]
Never mind color was set to high in sprite sheet, problem solved close thread. :)

**Comment by ProgSys** [comment]
No problem, its nice to see people using the tool.
