### ISSUE TITLE
TALK.DAT

### ISSUE THREAD

**Issue by Curokawa** [ProgSys/pg_disatools#12]
All dialogue in TALK.DAT, how extracting text? (talk,dat already extracted.)

**Comment by ProgSys** [comment]
I currently don't have any tool to open TALK.DAT. As far I remember TALK.DAT dosn't only contain text but also script's. This makes it more complicated to handle.
Maybe if Krisan Thyme post's some description on how the file is constructed then someone could implement a tool for it.

**Comment by ProgSys** [comment]
What you can do thogh, is open TALK.DAT in notepad++ (https://notepad-plus-plus.org/) and then set the encoding to "Shift JIS" under `encoding > character set > japanese > ShiftJIS`. This way you should see some of the text.
