### ISSUE TITLE
HD Image guide

### ISSUE THREAD

**Issue by sutebenukun** [ProgSys/pg_disatools#14]
Thanks a ton for the guide! Unfortunately I have a few questions,

I tried following your guide along with your Pleinar replacement and I seem to come across a number of issues.
I was perfectly able to extract the sprites I needed to change (I want to try to update every sprite into an HD version for the first disgaea) but when it comes to actually importing the sprite, it keeps telling me I have way too many colors, even after I compressed the colors down to 31 in GIMP (so that the background color would equal 32) but even that didn't help much.

Also, I was wondering if there's a particular format the sprites need to be in, in order to replace them. In the guide I can only see one sprite of Pleinar, was that the only sprite that was imported on your 6th tab? I was a bit unclear about that. 

The character I'm attempting to change at the moment is turning the old SD sprite of the Celestial Host into the HD sprite of the Male Celestial Host. Any help with this would be very appreciated and wonderful!

**Comment by ProgSys** [comment]
First make sure that your sprite sheet is set to 32 colors. At the top it should read how many colors can be used and the number can be changed by clicking on the 'gear' icon. 
Also if you export your image out of gimp make sure that your format (or settings) isn't a lossy compression as the colors wouldn't stay the same as in gimp. For example if you export it as jpeg then the colors would most likely change:
![img](https://tylerbrownblog.files.wordpress.com/2016/06/example-of-lossy-compression.png)

If none of this helps then maybe you could share the image that you are trying to import, then I could try it for myself and detect the error.

Yes, in the tutorial I only imported and replaced a singular sprite, just to demonstrate how it works. Importing more sprites works the same.
