### ISSUE TITLE
Offset reading of file

### ISSUE THREAD

**Issue by klterminator** [ProgSys/pg_disatools#15]
Hello.

I was wondering if it's possible to change the reading offset of file. For example, I'm trying to edit the title of a character in the file CHAR_E.DAT, but the new title is one character too long for the file. And when using notepad++ to write the new title directly, or data editor after changing how to read CHAR.DAT files, it become awful due to displacement of data.

If I have to edit SCRIPT.DAT to do that, how can I do it? Because it's not readable by data editor and when using the Disgaea Toolpack, the SCRIPT.DAT file is extracted in .bin files. How can I open it?

**Comment by ProgSys** [comment]
SCRIPT.DAT can't be edited with my tools as it contains not just a simple table, but a a farly complex scripting language. Currently nobody documented its construction to a degree that would make the creation of a tool feasible.

CHAR_E.DAT is a table where each column has maximum size defined by the game. The _title_ can only contain a maximum of 26 bytes of ShiftJis chars. Eeah ShiftJis char is 2 bytes big, so the _title_ can only be 13 chars long.

You can edit TALK.DAT using Disgaea PC Toolpack: [http://steamcommunity.com/app/405900/discussions/4/371918937281416805/](http://steamcommunity.com/app/405900/discussions/4/371918937281416805/)

Sadly many things in this game are hardcoded and therefore are very hard to change.
