### ISSUE TITLE
Some bugs with Sprite Sheet Editor v0.3.9 alpha

### ISSUE THREAD

**Issue by satsukiyatoshi** [ProgSys/pg_disatools#17]
Hello.
I'm currently using Sprite Sheet Editor v0.3.9 alpha to upscale all the sprites from ANM00.DAT.
I've processed all the "major" sprites so far (from 0001_LAHARL.SH to 3500_PLEINAIR.SH) and i found 3 files witch aren't processed well:

-1001_FILE.SH, opens wellbut can't save it Sprite Sheet Editor crash at save even whitout modification
-2210_PRINNY.SH and 2220_FILE.SH seems have a palette importation bugs*

*for the palette bug here's how i have processed all the other sprite witouht any bug to preserve the original 16 colors palette:
1)make one png from all sheet of a sprite
2)extract uniques colors and make a palette form them
3)2xbrz the extracted sheets
4)reduct the 2xbrz files to 16 colors
5)apply the original palette (extracted in 2)
6)import sheet as colors
only with 2210_PRINNY.SH and 2220_FILE.SH i get the message of "color missing ..." and so it's messing up the colors...

Thanks again

**Comment by ProgSys** [comment]
Sorry writing this late. I was gone. I will now look into this.

**Comment by satsukiyatoshi** [comment]
By the way i found another bug.
Some of the sprites of the sub animation are not well processed or misalignend.
for exemple in ANM01.DAT, the 5103:
![screenshot008](https://user-images.githubusercontent.com/8547498/34080785-a8d58abe-e343-11e7-84ed-939a69fe0a45.png)
The 6 to 10 picture aren't well processed.
I can extract and import png, but if i save the sprite and replace it in ANM01.DAT (with or without any modification) the animation freeze in game (the game don't crash but the animation don't works it's a simple picture instead of an animation.
You can easily test it because the 5103 from ANM01.DAT is used in the first scene of the game)

i've processed ANM01.DAT to ANM10.DAT and found also the ANM04.DAT (5703 file) and ANM06.DAT (5023 file) have the same bug

thanks again

**Comment by ProgSys** [comment]
I was able to reproduce it, I will have a look at it as well.

I will probably rewrite the import and make it a bit smarter.

**Comment by satsukiyatoshi** [comment]
Ok cool.
If you rewrite some of the code, could you add an option to choose the resize algorithm used when you use the "resize sprite" option (could help me a lot for my project to xbrz resize in the sprite tool instead of extract, resize, restore palette, import, save)

Thanks again for your tools

**Comment by ProgSys** [comment]
I uploaded a new version with improved color import.
It is now able to automatically reduce colors (but not necessary in the best possible way) and to automatically reassigned the colors of the image to the present in the color table.

Example:
![steps-new_color-import](https://user-images.githubusercontent.com/4257741/34328190-6bc8902c-e8d8-11e7-8f61-a748dcb9b5ff.png)

I may add xbrz a bit later.

Why 5103 is misalignend i didn't find out yet, but I am looking at it right now.

**Comment by satsukiyatoshi** [comment]
The auto color reduction + palette conservation seems to works great, thanks !
A great addon to the soft (not to hard to do i think) would be to be able to set default action (a specific value or "ask me") for the "resize the sprite, resize te sheet, decrease colors".... so when you import sheet as color it's auto apply your settings ^^

thanks again for your works

**Comment by satsukiyatoshi** [comment]
Any news of the alignement bug ?
Thanks a lot

**Comment by ProgSys** [comment]
Its a bit late, but good news! The alignement bug and 1001_FILE.SH export crash are fixed.
