### ISSUE TITLE
Imy Decompression?

### ISSUE THREAD

**Issue by resistthis13** [ProgSys/pg_disatools#2]
I know it may be the exact same case as the mpps when they were first mentioned, but just wanted to point out... I saw the changelog said:

"\* Added right click menu list entries
    - If it is a IMY compressed package you can decompress it"

But I can't seem to actually decompress them, the new icon appears, but I have no decompress option upon right clicking IMY files...

**Comment by ProgSys** [comment]
Well you can currently only decompress the top level package (like START.DAT inside SUBDATA.DAT). I could add a function to decompress a IMY file itself, but it wouldn't give you much, as multiple IMY files build one file, as far i know.

**Comment by marcussacana** [comment]
@ProgSys  to don't create another issue, i'm trying extract a imy here
but how i can extract?
first i try the TX2Converter, but don't looks wrong :/
[177:ERROR] Unknown compression type 'imy'! Only 'DXT1', 'DXT5' and 'BGRA' are supported!
(it's from other game, but looks the same engine...)
--edit
I tried find in the source and looks is from the FileManager, but the biggest change from my game format is the .dat packget, he can't read and so i can't extract... you can create command line just to convert IMY files?

**Comment by ProgSys** [comment]
Well in Disgaea a single IMY doesn't necessarily contain 1 one or multiple files. Instead it may only contain parts of it as the algorithm splits the entire data into chunks of same size, and every chunk gets compressed with IMY. To properly reconstruct the data you need all of the chunks.

It's why the decompress option is only avalable, on the **root** file itself in the FileManager:
![decompress](https://dl.dropboxusercontent.com/u/33065226/disgaea/wiki/IMY/decompress.png)
(This of course can be changed)


Also I can't say if your IMY is the same as in Disgaea, it may be completely different or be a different version.
So I would need to look into your .dat package to be able to tell. If it is different format, then it can take a while as compression is very hard to decipher, to some degree it's almost like encryption.

So maybe you can send me the package or tell me the game name, maybe I have the game already.

**Comment by marcussacana** [comment]
it's from criminal girls; Steam Version
i write this code to extract/reapack (i don't test my repack)
https://gist.github.com/marcussacana/723edd2d54889513f564976d13a3e8e8

**Comment by ProgSys** [comment]
On first look your IMY files are images, they start with a color table and continue with the color references.

**Comment by ProgSys** [comment]
At first look, I think your IMY files are compressed textures. At the beginning of the files you can see what looks like a color table, also they are referenced as textures:
`
	"textures":
	[
		"alic_0_01.imy",
		"alic_0_02.imy",
		"alic_0_03.imy",
		"alic_0_04.imy",
		"alic_4_01.imy",
	],
`

**Comment by makc-ar** [comment]
@marcussacana 
https://github.com/talestra/talestrakt/blob/master/game-criminalgirls/src/com/talestra/criminalgirls/IMY.kt

**Comment by marcussacana** [comment]
@makc-ar  thx, and what is this language?...
kotlin... my first time seeing this language, how i can compile?

**Comment by makc-ar** [comment]
@marcussacana 
Maybe Java?

**Comment by ProgSys** [comment]
They use Live 2D for there animations, you can even open them in the viewer:

![preview](https://dl.dropboxusercontent.com/u/33065226/game/hime.png)

**Comment by marcussacana** [comment]
the sdk of live2d is free?

**Comment by ProgSys** [comment]
There is a free viewer, the sdk itself has a 30 days trials version.
Also my first try to decompress a image:
![img](https://dl.dropboxusercontent.com/u/33065226/game/first%20try.png)

**Comment by marcussacana** [comment]
i see... hmm to make a unc patch don't looks easy...

**Comment by ProgSys** [comment]
It seems to be almost correct, but it looks like it is cut in half:
![img](https://dl.dropboxusercontent.com/u/33065226/game/second%20try.png)
I am out for today, will work tomorrow on it.

**Comment by marcussacana** [comment]
oka ^^
