### ISSUE TITLE
Add support DATA.DAT from the PSP version

### ISSUE THREAD

**Issue by Darkmet98** [ProgSys/pg_disatools#20]
Technically, the PSP version is the same version (on files inside the data.dat) from the pc port.
There's any possibility to add the DATA.DAT support to the PSP release?
Thanks.
(If you need any help to add the psp support to the program I can help you, but I don't know to programming on C++ xD, only Java and C#)

**Comment by ProgSys** [comment]
Sure it is possible to add it, if it is any similar to the pc version then it should be fairly easy.

C++ is actually similar to Java, minus the memory management, the hardest part is to get the project to run. To set up the compiler and IDE. If need be I can write a small tutorial.

**Comment by Darkmet98** [comment]
Sorry for the inactivity, I am busy with the finals from my high school.

Ok, the names are from the executable? (in the case on PC Version)
https://github.com/ProgSys/pg_disatools/blob/master/resources/START.DAT.csv

And sorry, I don't have too much time for learning another languaje xD I'm writting the tool for translating the TALK.DAT and executable strings since 5 months ago on my free times xD.
https://github.com/Darkmet98/Pleinair

**Comment by ProgSys** [comment]
START.DAT does not contain any file names. To make it easier to know what the files are we named them using the .csv file.
