### ISSUE TITLE
Support for Disgaea 1 Complete (Switch) .DAT files?

### ISSUE THREAD

**Issue by EvenIllusion** [ProgSys/pg_disatools#22]
Hello,

I was wondering, since the file structure for D1C seems to be so similar to Disgaea PC's, if it is possible to add support to extract/repack its .DAT files in the File Manager.

At present I don't seek to mess with its sprites, but rather just character or item parameters, and I don't expect the Data Editor to work, even if the subfiles are successfully extracted. I'm prepared to do my edits manually through hex, and perhaps even help map it out, but I have 0 knowledge about compression.

Thank you for your time!

**Comment by ProgSys** [comment]
Sadly I do not own a Switch and do _not_ plan to get the game by other means.
The only thing I can offer is that you research the file structure yourself and when you got it, you can send it over and I could add it.

**Comment by EvenIllusion** [comment]
Understandable!
I do own one and have access to the files, like the D1C SUBDATA.DAT. May I contact you somewhere else to try to work something out?

**Comment by ProgSys** [comment]
Sure, you can contact me on Steam or Discord. My name is the same there.

**Comment by EvenIllusion** [comment]
I've sent you a request on Steam! My name is Gezel.
