### ISSUE TITLE
future plan for d2 and phantom brave?

### ISSUE THREAD

**Issue by chocosobo** [ProgSys/pg_disatools#23]
i thought u quite but i found u still working on it
i wanna import sprites from phantom brave

there's sprites from old PS2 version without sidestory charaters and items

with current version v0.9.4 alpha
i got background images as .dds file
but cant find sprites, icons or portraits

any future plan for other PC ported old nipponichi games?

**Comment by ProgSys** [comment]
Right now not really, maybe one day.
