### ISSUE TITLE
DUNGEON.DAT/TALK.DAT Location

### ISSUE THREAD

**Issue by Blizihguh** [ProgSys/pg_disatools#25]
The [project wiki](https://github.com/ProgSys/pg_disatools/wiki/DUNGEON.DAT) says DUNGEON.DAT can be found inside SUBDATA.DAT > START.DAT. However, when I extract START.DAT using the file manager, it only contains IMY files. I've tried poking around in DATA.DAT and SUBDATA.DAT, but still can't find them. 

My main goal here is to find the battle scripts (SCRIPT.DAT/SCRIPT.BIN) and TALK.DAT, which are mentioned in the wiki but with no location specified. Ultimately I'm just trying to change which songs play on specific maps, with an eye towards re-adding The Invasion From Within and (hopefully) One With The Stars. I'd like to include the English version of Red Moon as well, although that's significantly easier (theoretically, you just replace SONG006.OGG in DATA.DAT).

Do you know where to find TALK.DAT/DUNGEON.DAT/etc?

**Comment by ProgSys** [comment]
You need to decompress it first: 
![grafik](https://user-images.githubusercontent.com/4257741/130118255-909bacee-8618-476f-8dd0-f022effc5bed.png)

Afterwards you can pack the decompress file, the game will work with it just fine.

**Comment by Blizihguh** [comment]
Thank you!
