### ISSUE TITLE
Map Viewer does not open GEO files with "NEW" textures.

### ISSUE THREAD

**Issue by GrounderGithub** [ProgSys/pg_disatools#27]
"[ERROR:PG_GEO::open:203]: Model 0 calculated data size is bigger then remainig file size!"  This does not apply to GEO files that are identical between both MPPs.

**Comment by ProgSys** [comment]
Yes, I sadly never bothered to implement the ability to open the HD versions.

**Comment by ProgSys** [comment]
I did actually find the problem, in my local version I can now open the "new" GEO files. But sadly my entire version is kinda brocken, because the code base is so old. No idea if I ever find the time to fix it.

**Comment by ProgSys** [comment]
I just noticed a funny thing. The HD ("NEW") model textures are compressed with DXT1. Which results in them looking far worse then the original color table textures, as some color steps are now lost and you can sometimes see the 4x4 compression block artifacts:
![grafik](https://github.com/ProgSys/pg_disatools/assets/4257741/2d5315bc-2e8f-47e8-bfec-5c347d388c40)
So the HD textures are actually worse in this instance... especially as the textuers are very small (64x64) so every pixel counts,

**Comment by GrounderGithub** [comment]
Well, if you do ever find the time, it'd be much appreciated,

**Comment by ProgSys** [comment]
Well I got it somewhat working again. And made you a dirty snapshot version of the tool:
https://www.dropbox.com/s/496mdsseivyrqy8/Disa%20Map%20Viewer%20v0.1.0%20snapshot.zip?dl=0
Its a bit Buggy, plus I don't even fully understand how the HD versions even work.
If you open a DATA.DAT file you can also now toggle to the HD version of the map.

**Comment by GrounderGithub** [comment]
Wow, thanks.  Seems to run really well!

**Comment by ProgSys** [comment]
I released a new stable version. HD versions should now work somewhat well, also now including Laharls castle.
