### ISSUE TITLE
Packing SUBDATA.DAT + Edit START.DAT

### ISSUE THREAD

**Issue by makc-ar** [ProgSys/pg_disatools#4]
Game: http://store.steampowered.com/app/405900
Hi! How to pack SUBDATA.DAT/START.DAT arhive? How to open SUBDATA.DAT/START.DAT?
Example START.DAT: https://yadi.sk/d/Gl8_XbRyrttJu

**Comment by ProgSys** [comment]
Click with right on "START.DAT" and select "Decompress" and save the decompressed file somewhere.
Then you can just open it. Note, you do not need to compress it back, you can just replace it.
![IMG](https://dl.dropboxusercontent.com/u/33065226/disgaea/decompress.png)

**Comment by makc-ar** [comment]
Thanks a lot, ProgSys! Please help: where game text is located? START.DAT/TALK.DAT or..? How to edit .DAT: TALK.DAT, CHARHELP.DAT, CHAR_EN.DAT?

**Comment by ProgSys** [comment]
That I don't know. Sorry. But there are some tools on the steam forum:
http://steamcommunity.com/app/405900/discussions/4/371918937281416805/

Disgaea Toolpack [DTP] seams to be able to edit TALK.DAT.

**Comment by merseus** [comment]
de casualidad sabes en donde se encuentran lo diálogos?.no los encuentro por ningún lafo

**Comment by ProgSys** [comment]
Merseus I sadly cant understand you...

**Comment by merseus** [comment]
do you happen to know where the dialogues are? of the PC version

**Comment by ProgSys** [comment]
Sorry I forgot about you. The dialog is located inside `Start.Dat > TALK.DAT`, but there is no easy tool right now to edit it: https://github.com/ProgSys/pg_disatools/issues/12

You can thogh open it in notepad++ and read it using "Shift JIS" encoding.
