### ISSUE TITLE
More of a suggestion... (Sprite Sheet Viewer)

### ISSUE THREAD

**Issue by Diefool** [ProgSys/pg_disatools#5]
I love being able to export sprites as .png

Can you reverse the process and add the functionality to import the .png back into the SH file after modifying. (And the possibility to edit the pallete via R G B scrolling and/or numerical entry?)

I didn't check details on if the pallete was exported (i know they use color palletes for the sprites)

I'm going through all the sprites and creating a table. They are exported by ID and I'm labelling them all with a name (and small description if needed). (I know...there are a crap ton and I'm bat-shit crazy to do this...not to mention all the duplicates...holy crap)... you can have this info if it would help you as well.

Found the following as well by sprite IDs:
50xx - System type sprites (transition animations, story-telling cutscene texts, etc.)
51xx - Laharl Sprites
52xx - Etna Sprites
53xx - Flonne Sprites
57xx - Prinny Sprites
58xx - Midboss (I think) Sprites

seems they follow that, I'm only up to ANM05.DAT got a lot of work ahead of me but that little bit of info might help :)

EDIT: See that KrisanThyme commited info similar to this, but the current release isnt exporting these sprite sheets with a generated name so I guess he added the major sprite sheets for battle? These are sprite animations used in cutscenes that I listed above by the way not battle.

Keep up the good work! Hope posting this as an "issue" doesn't hurt anything,

PS: Also, in the File Manager, can we get a "Decompress Selected" option so we can mass select the ANM##.DAT and START.DAT get them all decompressed and extracted easily? I have to right click and click decompress on all 100 files individually

**Comment by ProgSys** [comment]
Importing a .png back is sadly not trivial, because originally the images are not RGB collor images, but 4 bit ID images. Color tables are then used for sections of the ID Image to translate it into a RGB image.
So it is not trivial to import a RGB image back.

Yes, I can add a mass decompress function.

**Comment by Diefool** [comment]
Thanks, I suppose this can be closed than :)

Also, is there a discussion forum that discusses use of this, as well as the tool from Krisan that modifies TALK.DAT and maybe other tools as well?

I mean outside the steam forum (I am aware of that one but the community at steam is not focal towards game modification/reverse engineering/hacking whatsoever)

**Comment by ProgSys** [comment]
Sadly writing a full blown sprite editor will take too much time for me, but I may think of something.

**Comment by Diefool** [comment]
It's no problem, was just curious.  I appreciate it very much and will look through the actual coding when I get a spare minute (more like spare 6 hours lol)

I'm personally a BASIC coder, but I can make most sense of cpp.

Either way, I've changed splash screens and the main menu background image with no problem so the tool works fantastic (as well as decompression of IMY and the display of sprite sheets...seriously, man, excellent work). Going to take a crack at dissecting these Geo files and finding the relation between MPD and MPP files.

Following the project closely, hopefully I find somewhere I can contribute on my ventures through the data files.

**Comment by ProgSys** [comment]
Just made a new version (v0.4.8) where you now can mass decompress files. Just select multiple files and select 'decompress' in the drop down menu, then you should be able to select a target folder.

**Comment by ProgSys** [comment]
Also the spritesheets whitch the game uses are actually located at "SUBDATA.DAT/START.DAT/ANM000.DAT". The other files seam to be leftovers, there are actually a lot of them.

**Comment by Diefool** [comment]
Not left-overs, they are animations used in cut-scenes and non-battle animations ;)

i.e. Story-Line Text that draws over the backdrops when beginning a new chapter, Laharl laying asleep and waking up (used in the intro cutscene when awaking from 2 year nap), prinnies sticking tongues out. and a bunch of other stuff there is just so much to go through I need to batch extract the 01-99 files to know more

Thank you so much on the location of the main animation package though, it would of been the last one I looked at lmao!

EDIT: There are also a lot of duplicates in the 01-99 files as well, though... the exact same sprite IDs (and they do contain the exact same data so it's not an error on the File Managers part, it was literally created like this for some odd reason...I can tell from data files the developers practiced a few unprofessional techniques...but what can you expect from an in-house engine... it was probably improved upon with the releases of future disgaea games)

EDIT2: New version works great, thanks for batch decompression

**Comment by makc-ar** [comment]
Version v0.4.9 alpha Fix link dropbox?

Error (404)
We can't find the page you're looking for.
Here are a few links that may be helpful:
Home
Help center
Sign in
Get a free account
Dropbox Pro
Dropbox Business

**Comment by ProgSys** [comment]
Sorry copyed the link wrong, it should work now.

**Comment by makc-ar** [comment]
**ProgSys**, thanks a lot!

**Comment by ProgSys** [comment]
I hope up to the end of the next week I will have a version which can actually save a .SH file.

**Comment by Diefool** [comment]
The progress is great so far!

**Comment by ProgSys** [comment]
The new version can now export a SH file, but it may need testing
